(function (root) {
  "use strict";

  var STORKREDSE = [
  "København",
  "København Omegn",
  "Nordsjælland",
  "Bornholm",
  "Sjælland",
  "Fyn",
  "Sydjylland",
  "Østjylland",
  "Vestjylland",
  "Nordjylland"
];

  var KOMMUNER = [
  "Aabenraa",
  "Aalborg",
  "Aarhus",
  "Albertslund",
  "Allerød",
  "Assens",
  "Ballerup",
  "Billund",
  "Bornholm",
  "Brøndby",
  "Brønderslev",
  "Dragør",
  "Egedal",
  "Esbjerg",
  "Faaborg-Midtfyn",
  "Fanø",
  "Favrskov",
  "Faxe",
  "Fredensborg",
  "Fredericia",
  "Frederiksberg",
  "Frederikshavn",
  "Frederikssund",
  "Furesø",
  "Gentofte",
  "Gladsaxe",
  "Glostrup",
  "Greve",
  "Gribskov",
  "Guldborgsund",
  "Haderslev",
  "Halsnæs",
  "Hedensted",
  "Helsingør",
  "Herlev",
  "Herning",
  "Hillerød",
  "Hjørring",
  "Holbæk",
  "Holstebro",
  "Horsens",
  "Hvidovre",
  "Høje-Taastrup",
  "Hørsholm",
  "Ikast-Brande",
  "Ishøj",
  "Jammerbugt",
  "Kalundborg",
  "Kerteminde",
  "Kolding",
  "København",
  "Køge",
  "Langeland",
  "Lejre",
  "Lemvig",
  "Lolland",
  "Lyngby-Taarbæk",
  "Læsø",
  "Mariagerfjord",
  "Middelfart",
  "Morsø",
  "Norddjurs",
  "Nordfyn",
  "Nyborg",
  "Næstved",
  "Odder",
  "Odense",
  "Odsherred",
  "Randers",
  "Rebild",
  "Ringkøbing-Skjern",
  "Ringsted",
  "Roskilde",
  "Rudersdal",
  "Rødovre",
  "Samsø",
  "Silkeborg",
  "Skanderborg",
  "Skive",
  "Slagelse",
  "Solrød",
  "Sorø",
  "Stevns",
  "Struer",
  "Svendborg",
  "Syddjurs",
  "Sønderborg",
  "Thisted",
  "Tårnby",
  "Tønder",
  "Vallensbæk",
  "Varde",
  "Vejen",
  "Vejle",
  "Vesthimmerland",
  "Viborg",
  "Vordingborg",
  "Ærø"
];

  var KOMMUNE_TO_STORKREDS = {
  "København": "København",
  "Frederiksberg": "København",
  "Dragør": "København",
  "Tårnby": "København",
  "Gentofte": "København Omegn",
  "Albertslund": "København Omegn",
  "Ballerup": "København Omegn",
  "Brøndby": "København Omegn",
  "Herlev": "København Omegn",
  "Gladsaxe": "København Omegn",
  "Hvidovre": "København Omegn",
  "Ishøj": "København Omegn",
  "Lyngby-Taarbæk": "København Omegn",
  "Høje-Taastrup": "København Omegn",
  "Glostrup": "København Omegn",
  "Rødovre": "København Omegn",
  "Vallensbæk": "København Omegn",
  "Helsingør": "Nordsjælland",
  "Hørsholm": "Nordsjælland",
  "Hillerød": "Nordsjælland",
  "Gribskov": "Nordsjælland",
  "Allerød": "Nordsjælland",
  "Fredensborg": "Nordsjælland",
  "Frederikssund": "Nordsjælland",
  "Halsnæs": "Nordsjælland",
  "Egedal": "Nordsjælland",
  "Furesø": "Nordsjælland",
  "Rudersdal": "Nordsjælland",
  "Bornholm": "Bornholm",
  "Guldborgsund": "Sjælland",
  "Lolland": "Sjælland",
  "Lejre": "Sjælland",
  "Køge": "Sjælland",
  "Kalundborg": "Sjælland",
  "Faxe": "Sjælland",
  "Greve": "Sjælland",
  "Næstved": "Sjælland",
  "Odsherred": "Sjælland",
  "Ringsted": "Sjælland",
  "Roskilde": "Sjælland",
  "Slagelse": "Sjælland",
  "Solrød": "Sjælland",
  "Sorø": "Sjælland",
  "Stevns": "Sjælland",
  "Vordingborg": "Sjælland",
  "Holbæk": "Sjælland",
  "Assens": "Fyn",
  "Faaborg-Midtfyn": "Fyn",
  "Kerteminde": "Fyn",
  "Langeland": "Fyn",
  "Middelfart": "Fyn",
  "Nordfyn": "Fyn",
  "Nyborg": "Fyn",
  "Odense": "Fyn",
  "Svendborg": "Fyn",
  "Ærø": "Fyn",
  "Billund": "Sydjylland",
  "Esbjerg": "Sydjylland",
  "Fanø": "Sydjylland",
  "Fredericia": "Sydjylland",
  "Sønderborg": "Sydjylland",
  "Varde": "Sydjylland",
  "Haderslev": "Sydjylland",
  "Vejen": "Sydjylland",
  "Vejle": "Sydjylland",
  "Aabenraa": "Sydjylland",
  "Tønder": "Sydjylland",
  "Kolding": "Sydjylland",
  "Norddjurs": "Østjylland",
  "Odder": "Østjylland",
  "Randers": "Østjylland",
  "Samsø": "Østjylland",
  "Skanderborg": "Østjylland",
  "Syddjurs": "Østjylland",
  "Aarhus": "Østjylland",
  "Horsens": "Østjylland",
  "Hedensted": "Østjylland",
  "Favrskov": "Østjylland",
  "Herning": "Vestjylland",
  "Holstebro": "Vestjylland",
  "Ikast-Brande": "Vestjylland",
  "Ringkøbing-Skjern": "Vestjylland",
  "Skive": "Vestjylland",
  "Silkeborg": "Vestjylland",
  "Struer": "Vestjylland",
  "Viborg": "Vestjylland",
  "Lemvig": "Vestjylland",
  "Læsø": "Nordjylland",
  "Frederikshavn": "Nordjylland",
  "Brønderslev": "Nordjylland",
  "Hjørring": "Nordjylland",
  "Jammerbugt": "Nordjylland",
  "Mariagerfjord": "Nordjylland",
  "Morsø": "Nordjylland",
  "Rebild": "Nordjylland",
  "Thisted": "Nordjylland",
  "Aalborg": "Nordjylland",
  "Vesthimmerland": "Nordjylland"
};

  function normalizeStorkreds(value) {
    if (!value || value === "N/A") return "";
    return value
      .trim()
      .replace(/K?benhavn(?!s)\s*Omegn/g, "K?benhavns Omegn");
  }

  function normalizeKommune(value) {
    if (!value || value === "N/A") return "";
    return value.trim();
  }

  function getStorkredsForKommune(kommune) {
    var key = normalizeKommune(kommune);
    return normalizeStorkreds(KOMMUNE_TO_STORKREDS[key] || "");
  }

  var exported = {
    STORKREDSE: STORKREDSE,
    KOMMUNER: KOMMUNER,
    KOMMUNE_TO_STORKREDS: KOMMUNE_TO_STORKREDS,
    normalizeStorkreds: normalizeStorkreds,
    normalizeKommune: normalizeKommune,
    getStorkredsForKommune: getStorkredsForKommune,
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = exported;
  } else {
    root.STORKREDS_DATA = exported;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
